import = ["~/.config/alacritty/rose-pine.toml"]

[window]
  opacity = 0.95

[font]
  normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
  bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
  italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
  size = 14.0

[env]
    TERM = "xterm-256color"
