import = ["~/.config/alacritty/rose-pine.toml"]

[font]
  normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
  bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
  italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
  size = 22.0

[env]
    TERM = "xterm-256color"
