general.import = ["~/.config/alacritty/rose-pine.toml", "~/.config/alacritty/monitors.toml"]

[window]
  opacity = 1

[font]
  normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
  bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
  italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }


[env]
    TERM = "xterm-256color"