import = ["~/.config/alacritty/rose-pine-moon.toml", "~/.config/alacritty/monitors.toml"]

[window]
  opacity = 1

[font]
  normal = { family = "JetBrainsMono", style = "Regular" }
  bold = { family = "JetBrainsMono", style = "Regular" }
  italic = { family = "JetBrainsMono", style = "Italic" }


[env]
    TERM = "xterm-256color"
