general.import = ["~/.config/alacritty/rose_pine_moon.toml"]

[window]
  opacity = 1

[font]
  normal = { family = "IosevkaNerdFontMono", style = "Regular" }
  bold = { family = "IosevkaNerdFontMono", style = "Bold" }
  italic = { family = "IosevkaNerdFontMono", style = "Italic" }
  size = 16

[env]
    TERM = "xterm-256color"
